### ISSUE TITLE
Impossible Shortest Path Sometimes Ignoring Holes?

### ISSUE THREAD

**Issue by ThomasSchellenbergNextCentury** [MrMinimal64/extremitypathfinder#23]
Hello,

I'm not sure if I'm doing something wrong here. I'm trying to make a path that should be impossible (and thus return None), but instead I'm getting a path that's ignoring a hole. Is this a mistake on my part, or a bug in the library? Thanks for your help.

Ubuntu 20.04
Python 3.8.5
extremitypathfinder 2.0.0

```python
env = PlottingEnvironment(plotting_dir='./tmp/')
env.store(
    [(5, 5), (-5, 5), (-5, -5), (5, -5)],
    [[(-5, 1), (-5, 2), (5, 2), (5, 1)]],
    validate=True
)
env.prepare()
path, length = env.find_shortest_path(
    (0, 0),
    (0, 4)
)
assert path == None # path is actually [(0, 0), (0, 4)]
```

![graph_path_plot_1609883109](https://user-images.githubusercontent.com/10994382/103703389-79503680-4f75-11eb-9c9b-ac747f83edcf.png)
![graph_plot_1609883109](https://user-images.githubusercontent.com/10994382/103703390-79503680-4f75-11eb-8802-e11e42fb5a55.png)
![map_plot_160988310](https://user-images.githubusercontent.com/10994382/103703391-79503680-4f75-11eb-99ae-40a69f308780.png)
![path_plot_1609883110](https://user-images.githubusercontent.com/10994382/103703392-79e8cd00-4f75-11eb-831b-522ba8a2e715.png)
![prepared_map_plot_1609883109](https://user-images.githubusercontent.com/10994382/103703393-79e8cd00-4f75-11eb-8d03-2ceeeb874f19.png)

**Comment by MrMinimal64** [comment]
Thanks for reporting this. It indeed looks like a bug. I will have a look into it.

**Comment by MrMinimal64** [comment]
I was able to resolve this issue. Please note that the way you have specified the input polygons, a path would be allowed due to the way the algorithms was implemented:
![graph_path_plot_1610035278](https://user-images.githubusercontent.com/15111305/103925780-5316cc00-5118-11eb-9886-403558f3207e.png)

In order to "block" the view the polygons must truly overlap like this:
![prepared_map_plot_1610034886](https://user-images.githubusercontent.com/15111305/103925938-8b1e0f00-5118-11eb-8d4f-584977f5ff4c.png)

**Comment by ThomasSchellenbergNextCentury** [comment]
This works for me. Thank you for your quick response!

**Comment by jannikmi** [comment]
Work progress tracked in https://github.com/jannikmi/extremitypathfinder/issues/24
